// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXI84yooH7YM8gdmsobkPL0c8h8RITJTQ',
    appId: '1:638452175415:web:ce369fb30cca4e9b1825b2',
    messagingSenderId: '638452175415',
    projectId: 'face-auth-c3c9f',
    authDomain: 'face-auth-c3c9f.firebaseapp.com',
    storageBucket: 'face-auth-c3c9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBskCuvZ7qS2zIdKm7QXGxX9fRm_wBHRpU',
    appId: '1:638452175415:android:fb80e2ca810a17f31825b2',
    messagingSenderId: '638452175415',
    projectId: 'face-auth-c3c9f',
    storageBucket: 'face-auth-c3c9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWVdQ-VrgwvtxUV_4YXvJEtM1zBXa0Ff0',
    appId: '1:638452175415:ios:d57c485ffc83c6151825b2',
    messagingSenderId: '638452175415',
    projectId: 'face-auth-c3c9f',
    storageBucket: 'face-auth-c3c9f.appspot.com',
    iosClientId: '638452175415-k91t76hi8l1193h9nkf6lprolgijrnd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWVdQ-VrgwvtxUV_4YXvJEtM1zBXa0Ff0',
    appId: '1:638452175415:ios:e4cd3379e7dbf7661825b2',
    messagingSenderId: '638452175415',
    projectId: 'face-auth-c3c9f',
    storageBucket: 'face-auth-c3c9f.appspot.com',
    iosClientId: '638452175415-6d71fmobcl0s45t45toeq0i6an0ml7l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceAuth.RunnerTests',
  );
}
